version: "3.4"

networks:
  dev:
    driver: bridge
services:
  keycloak-db:
    container_name: keycloak-db
    image: docker.io/bitnami/postgresql:15.3.0
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=bitnami_keycloak
    volumes:
      - 'keycloak_db_data:/bitnami/postgresql'
  keycloak:
    container_name: keycloak
    image: docker.io/bitnami/keycloak:22
    depends_on:
      - keycloak-db
    ports:
      - "9001:8080"
    environment:
      - KEYCLOAK_DATABASE_HOST=keycloak-db
      - KEYCLOAK_DATABASE_USER=postgres
      - KEYCLOAK_DATABASE_PASSWORD=postgres
      - KEYCLOAK_ADMIN_USER=user
      - KEYCLOAK_ADMIN_PASSWORD=bitnami
volumes:
  keycloak_db_data:
    driver: local 